# Serial device path and baud rate
serial = { dev_path = "/dev/ttyACM0", baud_rate = 115200 }
# Unix (datagram) socket address bound by this program for receiving data
bind_socket = "/tmp/serial_mux.sock"

# One routing/forwarding rule
[[routes]]
# If header matches, send to this Unix (datagram) socket
socket_path = "/tmp/serial_vision.sock"

# Configuration for incoming data format from serial port
upstream = {
  # header frame (only 2 u8 supported)
  header = [0x4D, 0x41],
  # data segment length, excluding header and crc
  data_len = 13,
  # optional field, if specified, can only be CRC16 or CRC32.
  # When crc feature is enabled, performs CRC validation on the packet, otherwise only acts as a placeholder
  # crc = "CRC16"
}

[[routes]]
socket_path = "/tmp/serial_nav.sock"
upstream = {
  header = [0x4D, 0x42],
  data_len = 17,
  # crc = "CRC16"
}

# More routing rules can be added below
